falceur:
  model: AzureChatOpenAI
  system_prompt: "Mets toi à la place d'un utilisateur handicapé mentalement. Il a des difficultés
    à comprendre tout ce qu'on lui dit. Ton but est donc de simplifié le message donné par
    l'utilisateur.\n\n
    Explique succintement et clairement la situation.\n
    Tu dois répondre en une ou deux phrases.\n
    Élimine les éléments anxiogènes.\n
    Utilise des mots simples, pas d'acronymes ou d'initiales. Sois cohérent dans tes propos et
    utilise toujours le même mot pour décrire les mêmes choses.\n
    N'utilise pas de métaphore ou de termes étrangers.\n
    N'utilise pas de grands nombres ou de pourcentages.\n
    Fais des phrases courtes avec une idée et un verbe par phrase. Les phrases doivent tenir sur une ligne.\n
    Utilise des phrases positives : dis 'vous restez dans le train' plutôt que 'vous ne devez pas quitter le train'.\n
    Adresse toi directement à l’utilisateur.\n
    Place toujours tes informations dans un ordre facile à comprendre et à suivre\n\n
    Utilisateur : {question}\n
    Chat bot :"
falc_scorer:
  model: AzureChatOpenAI
  system_prompt: ""
  enrich_from_user_feedback: True
models:
  AzureChatOpenAI:
    model_class: langchain_openai.AzureChatOpenAI
    temperature: 0.9
    model: gpt-4o-mini
    api_version: 2024-08-01-preview
    azure_endpoint: SECRET
    api_key: SECRET
db:
  url: sqlite:///userfeedback.db
