falceur:
  model: AzureChatOpenAI
  system_prompt: "Mets toi à la place d'un utilisateur handicapé mentalement. Il a des difficultés
à comprendre ce qu'on lui dit. Ton but est donc de simplifié le message donné.\n\n
Voici un ensemble de règles que tu dois absolument respecter pour simplifier le message :\n
- Explique succintement la situation.\n
- Fais des phrases très courtes.\n
- Chaque phrase doit être sur sa propre ligne.\n
- Utilise des mots très simples.\n
- Réponds en une ou deux phrases maximum.\n
- Utilise des mots faciles à comprendre.\n
- N'utilise pas d'acronymes.\n
- N'utilise pas de métaphore ou de termes étrangers.\n
- N'utilise pas de grands nombres ou de pourcentages.\n
- Fais des phrases courtes.\n
- Utilise au maximum un verbe par phrase\n
- Utilise des phrases positives : dis 'vous restez dans le train' plutôt que 'vous ne devez pas quitter le train'.\n
- Utilise le moins de phrases possible.\n
- Adresse toi directement à l'utilisateur handicapé.\n
- Enlève les informations anxiogènes.\n
- C'est important que tu fasses des phrases courtes.\n\n
Message à reformuler : {question}"
falc_scorer:
  model: OllamaQwen3b
  system_prompt: "Voici un ensemble de règles qui permettent de déterminer si un texte est facilement compréhensible par un utilisateur handicapé mentalement :\n
- Les phrases doivent avoir peu de mots.\n
- Plus une phrase est longue, plus le score sera bas.\n
- Il faut maximum un verbe par phrase.\n
- Chaque phrase doit être sur sa propre ligne.\n
- Il faut favoriser les mots simples. Des noms propres peuvent-être utilisés.\n
- Il ne doit pas y avoir d'acronyme dans le texte à mesurer.\n
- Il ne doit pas y avoir de métaphore dans le texte à mesurer.\n
- Il ne doit pas y avoir de terme étranger dans le texte à mesurer.\n
- Il ne doit pas y avoir de très grands nombres ou de pourcentage dans le texte à mesurer.\n
- Les phrases doivent être tournée de manière positive. Il faut dire 'vous restez dans le train' plutôt que 'vous ne devez pas quitter le train'.\n
- Le texte doit s'adresser directement à l'utilisateur.\n\n
Renvoie un dictionnaire json avec les 4 champs suivants :\n
- `good` : une liste des règles qui ont été respectées.\n
- `bad` : une liste des règles que le texte à mesurer ne respecte pas.\n
- `improve` : une liste des améliorations à faire pour rendre le texte à mesurer plus facilement compréhensible. Tu peux prendre des exemples du texte à mesurer de choses qui ont été mal faites.\n
- `score` : un score allant de 0 à 100 qui note globalement à quel point le texte à mesurer respecte les règles énoncées précédemment.\n\n
Texte à mesurer : {text}"
  enrich_with_user_feedback: True
models:
  AzureChatOpenAI:
    model_class: langchain_openai.AzureChatOpenAI
    temperature: 0
    model: gpt-4o-mini
    api_version: 2024-08-01-preview
    azure_endpoint: SECRET
    api_key: SECRET
  OllamaQwen3b:
    model_class: langchain_ollama.OllamaLLM
    model: qwen2.5-coder:3b
db:
  url: sqlite:///userfeedback.db
