"""create-table-user-feedback

Revision ID: a44fa3745465
Revises: 
Create Date: 2024-11-22 11:06:04.542318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a44fa3745465"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "falc_user_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("non_falc_text", sa.String(), nullable=False),
        sa.Column("falc_text", sa.String(), nullable=False),
        sa.Column("understood", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("falc_user_feedback")
    # ### end Alembic commands ###
